version: '3.8'

services:
  chainlink-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ../../avalanche_chainlink_feeds.csv:/app/avalanche_chainlink_feeds.csv:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); http.get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }).on('error', () => process.exit(1));"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chainlink-api.rule=Host(`chainlink-api.localhost`)"
      - "traefik.http.services.chainlink-api.loadbalancer.server.port=3000"